### ISSUE TITLE
Unable to establish SSL connection.

### ISSUE THREAD

**Issue by meikobay** [zbzhu99/NGSIM_SMARTS#12]
**High Level Description**
[Describe what your goal is]

**Operating System**
[ macOS Mojave, ubuntu 20.04... windows 97]

**Problems**
[Describe in detail the problems you are facing]
I want do step two to get the date  wget https://jbox.sjtu.edu.cn/v/link/view/75a0931a222347e1ba2e0441407f4a1f,

**Comment by zbzhu99** [comment]
The repository is created for SJTU AI3601 course work. To download from jbox.sjtu.edu.cn, you should first connect to the SJTU campus network.

We appreciate your interest in this project. You can download the resource file from the external link: https://drive.google.com/file/d/14j5S8lGir9J5QAl8AHMamDu3WTDQAQc3/view?usp=sharing

Feel free to contact us if you have any problems.

**Comment by meikobay** [comment]
> The repository is created for SJTU AI3601 course work. To download from jbox.sjtu.edu.cn, you should first connect to the SJTU campus network.
> 
> We appreciate your interest in this project. You can download the resource file from the external link: https://drive.google.com/file/d/14j5S8lGir9J5QAl8AHMamDu3WTDQAQc3/view?usp=sharing
> 
> Feel free to contact us if you have any problems.

THKs
