### ISSUE TITLE
Encountered EOFError: Ran out of input while loading expert.pkl

### ISSUE THREAD

**Issue by CZtheHusky** [zbzhu99/NGSIM_SMARTS#5]
**High Level Description**
The expert.pkl is generated by example_expert_generator.py.
Created an empty txt file first and renamed it as expert.pkl. Then I ran example_expert_generator.py in the console. After 2 hours I got a huge expert.pkl (1.67 GB (1,803,748,055 bytes)). Followings are the details of the file.

名称: expert.pkl
大小: 1803748055 字节 (1720 MiB)
CRC32: 77EF6CCD
CRC64: E431186D7EF9D59A
SHA256: 172411701e1e47e799ae1f2f9c589729d159bc70836a6d1203eca482fcc19b32
SHA1: 5b5ec77b625ae06356875588cd6cb9b268afd430
BLAKE2sp: 36b7e67198d781210ec73aee6a3fdd01838fe24a6c4d9b95fc57f0ccc2082bac

**Operating System**

**Problems**
Then I tried to load it, but an error occurred: EOFError: Ran out of input

> with open("../expert.pkl", "rb") as f:
        experts_trajectory = pickle.load(f)

**Comment by zbzhu99** [comment]
The size of `expert.pkl` seems fine to me. You do not need to create the empty file first since `open` function in python will create the file automatically. Please check if you specify the correct path to your huge `expert.pkl` file rather than the empty file you created in advance.

**Comment by zbzhu99** [comment]
Please check if this can help: https://github.com/zbzhu99/NGSIM_SMARTS/issues/6#issuecomment-995707944
